name: CI/CD Pipeline

on:
  push:
    branches:
      - main
      - assignment1
  pull_request:
    branches:
      - main
      - assignment1

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.8'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Set PYTHONPATH
        run: echo "PYTHONPATH=$PYTHONPATH:$(pwd)/src" >> $GITHUB_ENV

      - name: Lint with flake8
        run: |
          pip install flake8
          flake8 src

      - name: Test with pytest
        run: |
          pip install pytest flask-testing
          pytest

      - name: Debug Secrets
        run: |
          echo "DOCKER_USERNAME length: ${#DOCKER_USERNAME}"
          echo "DOCKER_PASSWORD length: ${#DOCKER_PASSWORD}"
        env:
          DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
          DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}

      - name: Log in to Docker Hub
        env:
          DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
          DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
        run: echo "${DOCKER_PASSWORD}" | docker login -u "${DOCKER_USERNAME}" --password-stdin

      - name: Build & Push Image
        run: |
          echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "codewithsameer" --password-stdin
          docker image build -t codewithsameer/mlops59:latest .
          docker push codewithsameer/mlops59:latest

      - name: Build & push Docker image
        run: docker build -t mlops59 .
             docker push mlops59:latest
